# Generated by Django 3.1.6 on 2021-02-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210218_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
