# Generated by Django 3.1.6 on 2021-02-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
